In [11]:
import pandas as pd
import numpy as np
import sklearn
location = 'loansmall.csv'
df = pd.read_csv(location)
df.head(None)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,1077501,1296599,5000,5000,4975.00000,36 months,10.65,162.87,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.00000,60 months,15.27,59.83,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.00000,36 months,15.96,84.33,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.00000,36 months,13.49,339.31,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.00000,60 months,12.69,67.79,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1075269,1311441,5000,5000,5000.00000,36 months,7.90,156.46,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1069639,1304742,7000,7000,7000.00000,60 months,15.96,170.08,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1072053,1288686,3000,3000,3000.00000,36 months,18.64,109.43,E,E1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1071795,1306957,5600,5600,5600.00000,60 months,21.28,152.39,F,F2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1071570,1306721,5375,5375,5350.00000,60 months,12.69,121.45,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1070078,1305201,6500,6500,6500.00000,60 months,14.65,153.45,C,C3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1069908,1305008,12000,12000,12000.00000,36 months,12.69,402.54,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1064687,1298717,9000,9000,9000.00000,36 months,13.49,305.38,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1069866,1304956,3000,3000,3000.00000,36 months,9.91,96.68,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1069057,1303503,10000,10000,10000.00000,36 months,10.65,325.74,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1069759,1304871,1000,1000,1000.00000,36 months,16.29,35.31,D,D1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1065775,1299699,10000,10000,10000.00000,36 months,15.27,347.98,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1069971,1304884,3600,3600,3600.00000,36 months,6.03,109.57,A,A1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1062474,1294539,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1069742,1304855,9200,9200,9200.00000,36 months,6.03,280.01,A,A1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1069740,1284848,20250,20250,19142.16108,60 months,15.27,484.63,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1039153,1269083,21000,21000,21000.00000,36 months,12.42,701.73,B,B4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1069710,1304821,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1069700,1304810,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1069559,1304634,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1069697,1273773,15000,15000,15000.00000,36 months,9.91,483.38,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1069800,1304679,15000,15000,8725.00000,36 months,14.27,514.64,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1069657,1304764,5000,5000,5000.00000,60 months,16.77,123.65,D,D2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1069799,1304678,4000,4000,4000.00000,36 months,11.71,132.31,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1047704,1278806,8500,8500,8500.00000,36 months,11.71,281.15,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194081,1578841,1847814,11100,11100,11100.00000,36 months,17.77,400.02,D,D1,...,NaN,NaN,NaN,NaN,NaN,NaN,27500.0,NaN,NaN,NaN
194082,1578871,1847846,7500,7500,7500.00000,36 months,11.14,246.04,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,11400.0,NaN,NaN,NaN
194083,1578875,1847850,22000,22000,22000.00000,60 months,19.72,579.45,D,D5,...,NaN,NaN,NaN,NaN,NaN,NaN,16600.0,NaN,NaN,NaN
194084,1578850,1847823,10000,10000,10000.00000,60 months,11.14,218.13,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,39000.0,NaN,NaN,NaN
194085,1578201,1846933,4425,4425,4425.00000,36 months,8.90,140.51,A,A5,...,NaN,NaN,NaN,NaN,NaN,NaN,9400.0,NaN,NaN,NaN
194086,1578845,1847818,7300,7300,7300.00000,36 months,7.90,228.42,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,22400.0,NaN,NaN,NaN
194087,1578856,1847830,6250,6250,6250.00000,36 months,10.16,202.14,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,8500.0,NaN,NaN,NaN
194088,1552693,1818874,10000,10000,10000.00000,36 months,12.12,332.72,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,16600.0,NaN,NaN,NaN
194089,1570658,1838259,9250,9250,9250.00000,36 months,15.80,324.29,C,C3,...,NaN,NaN,NaN,NaN,NaN,NaN,8800.0,NaN,NaN,NaN
194090,1564120,1831618,7000,7000,7000.00000,36 months,10.16,226.40,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,42500.0,NaN,NaN,NaN
194091,1579023,1847975,14675,14675,14675.00000,36 months,14.09,502.20,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,18079.0,NaN,NaN,NaN
194092,1578763,1847726,12000,12000,12000.00000,36 months,12.12,399.26,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,9100.0,NaN,NaN,NaN
194093,1579018,1847969,5275,5275,5275.00000,36 months,8.90,167.50,A,A5,...,NaN,NaN,NaN,NaN,NaN,NaN,68000.0,NaN,NaN,NaN
194094,1553044,1819231,23500,23500,23500.00000,60 months,20.49,629.04,E,E1,...,NaN,NaN,NaN,NaN,NaN,NaN,18400.0,NaN,NaN,NaN
194095,1579002,1847953,10000,10000,10000.00000,36 months,14.09,342.22,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,21400.0,NaN,NaN,NaN
194096,1477178,1734798,15000,15000,15000.00000,36 months,7.62,467.43,A,A3,...,NaN,NaN,NaN,NaN,NaN,NaN,56800.0,NaN,NaN,NaN
194097,1578784,1847750,4375,4375,4375.00000,36 months,12.12,145.57,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,7300.0,NaN,NaN,NaN
194098,1561362,1828302,20050,20050,20050.00000,36 months,6.62,615.61,A,A2,...,NaN,NaN,NaN,NaN,NaN,NaN,46400.0,NaN,NaN,NaN
194099,1578964,1847710,20000,20000,20000.00000,36 months,7.90,625.81,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,86297.0,NaN,NaN,NaN
194100,1576118,1844945,5000,5000,5000.00000,60 months,15.31,119.77,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,52600.0,NaN,NaN,NaN
194101,1578752,1847715,15350,15350,15350.00000,36 months,14.09,525.30,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,7100.0,NaN,NaN,NaN
194102,1578735,1847500,6000,6000,6000.00000,36 months,16.29,211.81,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,30462.0,NaN,NaN,NaN
194103,1578534,1847676,5500,5500,5500.00000,36 months,12.12,183.00,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,29300.0,NaN,NaN,NaN
194104,1578522,1847663,30000,30000,29750.00000,36 months,18.75,1095.90,D,D3,...,NaN,NaN,NaN,NaN,NaN,NaN,41400.0,NaN,NaN,NaN
194105,1578517,1847658,3400,3400,3400.00000,36 months,6.03,103.49,A,A1,...,NaN,NaN,NaN,NaN,NaN,NaN,10700.0,NaN,NaN,NaN
194106,1578738,1783058,8000,8000,8000.00000,36 months,15.31,278.54,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,15000.0,NaN,NaN,NaN
194107,1572131,1840206,12350,12350,12350.00000,36 months,6.62,379.20,A,A2,...,NaN,NaN,NaN,NaN,NaN,NaN,65000.0,NaN,NaN,NaN
194108,1573779,1841705,19700,19700,19450.00000,36 months,14.09,674.17,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,26700.0,NaN,NaN,NaN
194109,1570647,1838247,15875,15875,15625.00000,36 months,14.09,543.27,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,11400.0,NaN,NaN,NaN
194110,1578497,1847637,12500,12500,12500.00000,36 months,15.80,438.23,C,C3,...,NaN,NaN,NaN,NaN,NaN,NaN,4200.0,NaN,NaN,NaN

In [12]:
df.shape

(194111, 74)

In [13]:
df.isnull().sum()

id                                  0
member_id                           0
loan_amnt                           0
funded_amnt                         0
funded_amnt_inv                     0
term                                0
int_rate                            0
installment                         0
grade                               0
sub_grade                           0
emp_title                       12177
emp_length                       7722
home_ownership                      0
annual_inc                          4
verification_status                 0
issue_d                             0
loan_status                         0
pymnt_plan                          0
url                                 0
desc                           106340
purpose                             0
title                              19
zip_code                            0
addr_state                          0
dti                                 0
delinq_2yrs                        29
earliest_cr_line                   29
inq_last_6mths                     29
mths_since_last_delinq         110561
mths_since_last_record         174057
                                ...
collection_recovery_fee             0
last_pymnt_d                      193
last_pymnt_amnt                     0
next_pymnt_d                   124325
last_credit_pull_d                 15
collections_12_mths_ex_med        145
mths_since_last_major_derog    162931
policy_code                         0
application_type                    0
annual_inc_joint               194111
dti_joint                      194111
verification_status_joint      194111
acc_now_delinq                     29
tot_coll_amt                    42536
tot_cur_bal                     42536
open_acc_6m                    194111
open_il_6m                     194111
open_il_12m                    194111
open_il_24m                    194111
mths_since_rcnt_il             194111
total_bal_il                   194111
il_util                        194111
open_rv_12m                    194111
open_rv_24m                    194111
max_bal_bc                     194111
all_util                       194111
total_rev_hi_lim                42536
inq_fi                         194111
total_cu_tl                    194111
inq_last_12m                   194111
Length: 74, dtype: int64

In [14]:
df1=df.dropna(axis=1,how='all')
df1.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim
0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,...,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,0.0,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,...,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,0.0,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,...,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,0.0,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,...,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,0.0,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,...,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,0.0,NaN,NaN,NaN

In [15]:
df2=df1.dropna()
df2.head(None)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim
42630,10089537,11941075,7500,7500,7500.0,36 months,11.99,249.08,B,B3,...,Feb-16,Jan-16,0.0,34.0,1,INDIVIDUAL,0.0,0.0,74029.0,10200.0
42667,10159240,12010878,16000,16000,16000.0,60 months,19.22,416.99,D,D4,...,Feb-16,Jan-16,0.0,60.0,1,INDIVIDUAL,0.0,0.0,188654.0,22600.0
42678,10159217,12010856,14125,14125,14125.0,60 months,19.22,368.13,D,D4,...,Feb-16,Jan-16,0.0,50.0,1,INDIVIDUAL,0.0,0.0,164310.0,12900.0
42759,9847366,11699256,12000,12000,12000.0,36 months,13.53,407.40,B,B5,...,Feb-16,Jan-16,0.0,58.0,1,INDIVIDUAL,0.0,0.0,222335.0,9800.0
43029,8978364,10780341,15600,15600,15600.0,36 months,8.90,495.36,A,A5,...,Feb-16,Jan-16,0.0,40.0,1,INDIVIDUAL,0.0,0.0,90719.0,21200.0
43373,10138317,9101659,24000,24000,24000.0,36 months,16.24,846.62,C,C5,...,Feb-16,Jan-16,0.0,40.0,1,INDIVIDUAL,0.0,4303.0,3401.0,13700.0
43564,10068005,11919752,10000,10000,10000.0,60 months,15.61,241.12,C,C4,...,Feb-16,Jan-16,0.0,50.0,1,INDIVIDUAL,0.0,0.0,18228.0,23700.0
44403,9924826,11776961,16500,16500,16500.0,36 months,11.99,547.96,B,B3,...,Jan-16,Jan-16,0.0,40.0,1,INDIVIDUAL,0.0,215.0,294390.0,20600.0
44495,10145728,11997783,13000,13000,13000.0,60 months,17.57,327.09,D,D2,...,Jan-16,Jan-16,0.0,73.0,1,INDIVIDUAL,0.0,0.0,9779.0,16700.0
44689,10096514,11948556,17000,17000,16850.0,36 months,12.85,571.57,B,B4,...,Jan-16,Jan-16,0.0,42.0,1,INDIVIDUAL,0.0,0.0,33835.0,13800.0
44773,10086431,11938463,15000,15000,15000.0,36 months,11.99,498.15,B,B3,...,Feb-16,Jan-16,0.0,35.0,1,INDIVIDUAL,0.0,0.0,12698.0,33300.0
44896,10136163,11988193,32875,32875,32875.0,60 months,22.90,924.88,E,E4,...,Jan-16,Jan-16,0.0,66.0,1,INDIVIDUAL,0.0,2613.0,326085.0,6400.0
45134,10065710,11917796,8000,8000,8000.0,36 months,15.61,279.72,C,C4,...,Jan-16,Jan-16,0.0,38.0,1,INDIVIDUAL,0.0,0.0,372373.0,20900.0
45469,10135603,8429070,7000,7000,6925.0,36 months,10.99,229.14,B,B2,...,Feb-16,Jan-16,0.0,74.0,1,INDIVIDUAL,0.0,804.0,24025.0,10800.0
45828,10085174,11937287,15000,15000,15000.0,36 months,19.97,557.23,D,D5,...,Jan-16,Jan-16,0.0,57.0,1,INDIVIDUAL,0.0,0.0,15342.0,23100.0
46214,10064664,11916809,5375,5375,5375.0,36 months,16.99,191.61,D,D1,...,Jan-16,Jan-16,0.0,74.0,1,INDIVIDUAL,0.0,0.0,75763.0,4500.0
46511,9858380,11710208,16000,16000,16000.0,36 months,13.98,546.69,C,C1,...,Feb-16,Jan-16,0.0,14.0,1,INDIVIDUAL,0.0,0.0,54034.0,31700.0
46558,9858442,11710267,9750,9750,9750.0,36 months,16.24,343.94,C,C5,...,Jan-16,Jan-16,0.0,45.0,1,INDIVIDUAL,0.0,0.0,22379.0,19130.0
46903,9894866,11747025,12000,12000,12000.0,36 months,13.53,407.40,B,B5,...,Feb-16,Jan-16,0.0,29.0,1,INDIVIDUAL,0.0,0.0,90907.0,9200.0
47116,9857842,11709701,16000,16000,16000.0,36 months,13.98,546.69,C,C1,...,Feb-16,Jan-16,0.0,68.0,1,INDIVIDUAL,0.0,0.0,31340.0,24900.0
47132,9877671,11729524,35000,35000,34950.0,60 months,21.48,956.35,E,E2,...,Feb-16,Jan-16,0.0,38.0,1,INDIVIDUAL,0.0,0.0,359329.0,26600.0
47142,9836663,11688630,12000,12000,12000.0,60 months,16.24,293.35,C,C5,...,Feb-16,Jan-16,0.0,40.0,1,INDIVIDUAL,0.0,0.0,473452.0,15600.0
47148,9755724,11607768,9800,9800,9775.0,36 months,12.85,329.50,B,B4,...,Feb-16,Jan-16,0.0,62.0,1,INDIVIDUAL,0.0,0.0,267259.0,6700.0
47212,9877667,11729520,8325,8325,8325.0,36 months,15.61,291.09,C,C4,...,Feb-16,Jan-16,0.0,21.0,1,INDIVIDUAL,0.0,0.0,131276.0,17000.0
47242,9787669,11639545,10000,10000,10000.0,36 months,14.98,346.56,C,C3,...,Feb-16,Jan-16,0.0,63.0,1,INDIVIDUAL,0.0,0.0,68334.0,9000.0
47267,9787624,11639501,10000,10000,9975.0,60 months,16.99,248.48,D,D1,...,Feb-16,Jan-16,0.0,135.0,1,INDIVIDUAL,0.0,405.0,30009.0,24800.0
47601,9857266,11709162,15000,15000,15000.0,36 months,12.85,504.33,B,B4,...,Feb-16,Jan-16,0.0,54.0,1,INDIVIDUAL,0.0,0.0,104994.0,12500.0
47714,9797105,11649068,15000,15000,15000.0,60 months,15.61,361.67,C,C4,...,Feb-16,Jan-16,0.0,75.0,1,INDIVIDUAL,0.0,0.0,31998.0,10500.0
48306,9816613,11668576,16000,16000,16000.0,60 months,16.99,397.56,D,D1,...,Feb-16,Jan-16,0.0,46.0,1,INDIVIDUAL,0.0,8950.0,98904.0,11600.0
48546,9845823,11697836,12000,12000,12000.0,36 months,7.90,375.49,A,A4,...,Feb-16,Jan-16,0.0,33.0,1,INDIVIDUAL,0.0,0.0,315644.0,17100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165657,3147749,3860111,6400,6400,6325.0,36 months,15.80,224.38,C,C3,...,Feb-16,Jan-16,0.0,49.0,1,INDIVIDUAL,0.0,0.0,182320.0,15200.0
166345,3345634,4147897,13000,13000,13000.0,36 months,17.77,468.49,D,D1,...,Feb-16,Jan-16,0.0,36.0,1,INDIVIDUAL,0.0,0.0,233026.0,21500.0
167988,3218888,3961603,16000,16000,15975.0,60 months,17.27,399.97,C,C5,...,Feb-16,Jan-16,0.0,26.0,1,INDIVIDUAL,0.0,0.0,92356.0,12100.0
168271,3241081,3984012,12000,12000,12000.0,36 months,15.80,420.71,C,C3,...,Feb-16,Jan-16,0.0,34.0,1,INDIVIDUAL,0.0,0.0,71379.0,18900.0
168350,3067079,3739727,4500,4500,4500.0,36 months,14.33,154.53,C,C1,...,Jan-16,Jan-16,0.0,73.0,1,INDIVIDUAL,0.0,0.0,31242.0,5000.0
168415,3220573,3963513,12000,12000,12000.0,36 months,10.16,388.11,B,B1,...,Feb-16,Jan-16,0.0,69.0,1,INDIVIDUAL,0.0,0.0,19891.0,17600.0
168484,3240061,3982887,9250,9250,9250.0,36 months,12.12,307.77,B,B3,...,Feb-16,Jan-16,0.0,58.0,1,INDIVIDUAL,0.0,0.0,9818.0,6600.0
169151,3217597,3960142,16000,16000,15950.0,60 months,17.27,399.97,C,C5,...,Feb-16,Jan-16,0.0,25.0,1,INDIVIDUAL,0.0,2937.0,47137.0,21800.0
170626,3163792,3876472,15000,15000,15000.0,36 months,8.90,476.30,A,A5,...,Feb-16,Jan-16,0.0,77.0,1,INDIVIDUAL,0.0,180.0,24073.0,40500.0
170915,3153966,3866680,5000,5000,5000.0,36 months,21.49,189.64,E,E3,...,Feb-16,Jan-16,0.0,56.0,1,INDIVIDUAL,0.0,777.0,10015.0,9300.0
171316,3151896,3864499,12000,12000,12000.0,36 months,14.09,410.66,B,B5,...,Feb-16,Jan-16,0.0,41.0,1,INDIVIDUAL,0.0,0.0,34285.0,17200.0
171370,3161611,3874193,19950,19950,19950.0,36 months,12.12,663.77,B,B3,...,Feb-16,Jan-16,0.0,37.0,1,INDIVIDUAL,0.0,0.0,90932.0,40600.0
173374,3095430,3767681,9450,9450,9450.0,36 months,16.29,333.59,C,C4,...,Jan-16,Jan-16,0.0,24.0,1,INDIVIDUAL,0.0,0.0,15996.0,13200.0
173878,2896721,3529121,24000,24000,24000.0,60 months,17.77,606.45,D,D1,...,Feb-16,Jan-16,1.0,67.0,1,INDIVIDUAL,0.0,101.0,300054.0,58200.0
174248,3064675,3736851,16450,16450,16450.0,60 months,16.29,402.58,C,C4,...,Feb-16,Jan-16,0.0,81.0,1,INDIVIDUAL,0.0,0.0,101044.0,48309.0
174302,3007581,3640071,8000,8000,8000.0,36 months,14.09,273.78,B,B5,...,Feb-16,Jul-15,0.0,46.0,1,INDIVIDUAL,0.0,0.0,7049.0,10700.0
174322,3007453,3639921,20000,20000,20000.0,60 months,24.70,583.52,G,G1,...,Feb-16,Jan-16,0.0,72.0,1,INDIVIDUAL,0.0,0.0,16374.0,20100.0
174347,3017180,3629639,12000,12000,11950.0,36 months,15.80,420.71,C,C3,...,Feb-16,Jan-16,0.0,49.0,1,INDIVIDUAL,0.0,436.0,65816.0,12400.0
174842,2984897,3607095,20000,20000,19975.0,36 months,12.12,665.44,B,B3,...,Jan-16,Jan-16,0.0,50.0,1,INDIVIDUAL,0.0,0.0,24197.0,16900.0
174924,3004641,3636808,5250,5250,5250.0,36 months,21.49,199.12,E,E3,...,Feb-16,Jan-16,0.0,29.0,1,INDIVIDUAL,0.0,0.0,34063.0,2500.0
176141,2864621,3466781,28200,28200,28100.0,60 months,17.27,704.95,C,C5,...,Feb-16,Jan-16,0.0,37.0,1,INDIVIDUAL,0.0,159.0,548379.0,8500.0
176183,2828705,3411363,16000,16000,16000.0,60 months,21.98,441.73,E,E4,...,Feb-16,Jan-16,0.0,43.0,1,INDIVIDUAL,0.0,0.0,28619.0,21900.0
176403,2827709,3410306,20675,20675,20675.0,36 months,12.12,687.90,B,B3,...,Feb-16,Jan-16,0.0,11.0,1,INDIVIDUAL,0.0,0.0,42341.0,10600.0
176785,2835999,3418380,19725,19725,19475.0,60 months,15.80,477.59,C,C3,...,Feb-16,Jan-16,0.0,60.0,1,INDIVIDUAL,0.0,0.0,71862.0,27272.0
178555,2383405,2846195,28000,28000,27950.0,60 months,23.28,793.85,F,F2,...,Feb-16,Jan-16,0.0,18.0,1,INDIVIDUAL,0.0,0.0,316479.0,12900.0
178965,2382561,2845301,15000,15000,15000.0,60 months,16.29,367.09,C,C4,...,Feb-16,Jan-16,0.0,17.0,1,INDIVIDUAL,0.0,0.0,635821.0,212900.0
179104,2381929,2844633,7200,7200,7200.0,60 months,19.72,189.64,D,D5,...,Feb-16,Jan-16,0.0,67.0,1,INDIVIDUAL,0.0,4416.0,53385.0,3600.0
179442,2380229,2842826,25250,25250,25225.0,60 months,17.27,631.20,C,C5,...,Feb-16,Jan-16,0.0,56.0,1,INDIVIDUAL,0.0,0.0,211673.0,24500.0
182318,2304802,2736978,20000,20000,19975.0,60 months,16.29,489.45,C,C4,...,Feb-16,Jan-16,0.0,81.0,1,INDIVIDUAL,0.0,0.0,22015.0,20600.0
186926,1826223,2128538,16000,16000,16000.0,60 months,18.75,412.86,D,D3,...,Feb-16,Jan-16,0.0,17.0,1,INDIVIDUAL,0.0,0.0,267822.0,22000.0

In [21]:
pd.pivot_table(df, index= 'addr_state',columns='grade', values= "member_id", aggfunc='count', fill_value= 0,
              margins = True, margins_name= 'Total')

grade           A      B      C      D      E     F     G   Total
addr_state
AK             87    167    134     93     50    15     4     550
AL            347    705    639    379    196    98    17    2381
AR            210    440    382    217     97    29     6    1381
AZ            675   1455   1136    608    309   136    40    4359
CA           5134  10311   8081   4910   2150   936   209   31731
CO            733   1322   1099    555    277   113    26    4125
CT            538   1010    782    428    245    93    17    3113
DC            120    211    147     98     56    24     5     661
DE             69    175    140     91     34    14     3     526
FL           2038   4228   3480   2055    859   388    98   13146
GA           1039   2071   1587    890    424   194    68    6273
HI            125    333    291    193     86    51     5    1084
IA              2      2      2      4      1     2     0      13
ID              1      3      4      2      1     0     0      11
IL           1156   2518   1998   1128    488   246    57    7591
IN            266    744    707    337    174    80    11    2319
KS            273    603    462    231    115    60    11    1755
KY            272    584    469    249    122    62    16    1774
LA            359    708    614    330    170    74    16    2271
MA            982   1603   1179    645    316   135    45    4905
MD            741   1389   1203    684    377   174    54    4622
ME              0      1      2      0      0     0     0       3
MI            670   1443   1206    729    315   138    33    4534
MN            551   1066    899    479    193    92    16    3296
MO            519   1031    868    430    205    87    24    3164
MS              6      7      7      4      2     2     0      28
MT             81    190    163     67     38    12     1     552
NC            734   1657   1385    788    383   179    32    5158
NE              1      1      1      7      3     1     0      14
NH            171    284    238    121     62    24    10     910
NJ           1245   2382   1996   1213    590   255    62    7743
NM            174    341    273    152     58    34    12    1044
NV            364    948    773    418    185    79    19    2786
NY           2522   5121   4344   2686   1222   562   134   16591
OH            913   2021   1686    902    424   195    47    6188
OK            252    601    458    236     99    49    15    1710
OR            393    932    659    370    143    67    12    2576
PA           1105   2127   1742   1038    477   236    34    6759
RI            145    261    221    120     67    20     3     837
SC            372    711    556    338    160    66    16    2219
SD             48    131    131     42     19     8     2     381
TN            240    654    616    315    171    73     8    2077
TX           2341   4713   3728   2224   1012   489   127   14634
UT            240    498    401    197    101    44    14    1495
VA            999   1882   1653    872    455   221    57    6139
VT             59     80     77     34     18     8     0     276
WA            665   1508   1246    667    304   155    35    4580
WI            388    815    652    314    149    77    17    2412
WV            153    289    272    140     70    25     6     955
WY             73    149    130     56     36    11     4     459
Total       30591  62426  50919  29086  13508  6133  1448  194111